### ISSUE TITLE
Can you use native HTML attributes within x-option

### ISSUE THREAD

**Issue by LiquidFlame** [thefrontside/emberx-select#105]
### Ember Version / Ember CLI Version:

**Ember Version: 2.1.0**
**Ember CLI Version: 1.13.13**

### Expected Behavior
I should first mention I am extremely new to Ember

I'm trying to include the native "disabled" attribute of a select option within the x-option.

The disabled attribute is a boolean attribute. When present, it specifies that an option should be disabled.

### Actual Behavior

The native "disabled" attribute doesn't seem to be processed at all. The work around that I have is by adding a "didInsertElement" into my component js, but ideally it would be better/easier if the x-option had some kind of disabled attribute like the native HTML select does.

`  didInsertElement: function () {
    this.$('option:first').attr('disabled', true);
  }`

### Steps To Reproduce:
1. Create an x-select
2. Create an x-option and try using the native HTML select option "disabled" attribute
3. Example: `  {{#x-option disabled value=defaultSelect}}
    {{defaultSelect}}
  {{/x-option}}`

**Comment by Robdel12** [comment]
Hi @LiquidFlame! 

You should be able to pass disabled to `x-option`. What does your template look like?

```hbs
{{#x-select value=something}}
  {{#x-option value=charles disabled=true}}Charles{{/x-option}}
  {{#x-option value=bastion}}Bastion{{/x-option}}
  {{#x-option value=stanley}}Stanley{{/x-option}}
{{/x-select}}
```

**Comment by LiquidFlame** [comment]
@Robdel12 

I'm dumb, I'm used to just throwing in "disabled" on the option tag and it working.

Didn't think to actually use "disabled=true" which does work.

Thanks.
