### ISSUE TITLE
x-select to support attributes similar to ember select

### ISSUE THREAD

**Issue by nagkumar** [thefrontside/emberx-select#109]
x-select to support attributes similar to ember select
    
e.g.

{{x-select value=selections multiple=false action="selectionsChanged" content=model.books optionValuePath="content.id" optionLabelPath="content.title" prompt="Please select a name ember x-select"}}

i.e. in similar lines to 
{{view "select"
  content=model.books
  optionValuePath="content.id"
  optionLabelPath="content.title"
  prompt="Please select a name ember select"
  value=2}}

**Comment by Robdel12** [comment]
Hi @nagkumar!

We specifically don't support that style of select. I think [Ted select](https://github.com/tedconf/ember-ted-select) is what you're looking for :)

**Comment by cowboyd** [comment]
There is also https://github.com/thefrontside/emberx-select-blockless, but as @Robdel12 said, the philosophy behind emberx-select is to map as closely to real HTML as possible and not take on the task of generating elements for you. We believe this explicit approach makes it more flexible and readable in the long run, but understandably it does require a few more lines of code.
