### ISSUE TITLE
Add support for missing attributes

### ISSUE THREAD

**Issue by jonkoops** [thefrontside/emberx-select#11]
Currently the `x-select` component supports a limited amount of the available attributes on a normal HTML select. The attributes that are currently not present on the component are as follows:

* autofocus
* form
* required
* size

For a complete overview of the available attributes and their functionality see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#attributes

Some of these attributes will probably not be applicable to most Ember applications (mostly `form` and `name`), but they should probably be added as well to support some edge cases. Other attributes like `required` and `autofocus` are obviously pretty useful.

I can whip up a pull request to add these attributes, but I wanted to do a quick check if anyone has issues with adding these attributes.

**Comment by cowboyd** [comment]
A pull request would be very much appreciated! There is #10 which is outstanding, but I think it makes sense to roll them all into one PR.
