### ISSUE TITLE
Emberx Select flashes/blinks on first click

### ISSUE THREAD

**Issue by trumb1mj** [thefrontside/emberx-select#116]
### Ember Version / Ember CLI Version: 

**Ember Version: 2.4.3**
**Ember CLI Version: 2.4.3**

### Actual Behavior

When clicking on an xselect for the first time, a flashing or blinking occurs.  This also occurs when clicking away and back on the xselect.

### Steps To Reproduce:
1. Create xselect
2. Click on it

### GIF of behavior
![xselect-bug](https://cloud.githubusercontent.com/assets/928274/14830823/4d881b54-0bb8-11e6-9926-c519ed6e2bf6.gif)

**Comment by Robdel12** [comment]
Hmm, this one is interesting. Is there anyway you can reproduce this? I have a feeling there's something interfering here.

**Comment by trumb1mj** [comment]
I can't seem to reproduce this in a bare bones project.  I'll try stripping dependencies away from my project to see if I can isolate where the conflict is.

I'm using a couple things that may cause issues: fastclick, jquery scroll wheel..? No idea though.

**Comment by trumb1mj** [comment]
Upgrading my version of jquery to 2.1 seemed to fix this.
