### ISSUE TITLE
Remove two way data binding by default

### ISSUE THREAD

**Issue by Robdel12** [thefrontside/emberx-select#120]
We should remove the two way databinding by default and only do DDAU. Basically it means removing [this line](https://github.com/thefrontside/emberx-select/blob/master/addon/components/x-select.js#L74), updating tests, and cutting a major version.

We should think about other major changes we want to make in 3.0

**Comment by dgaus** [comment]
Could we add an parameter to disable two way binding in the meanwhile?

**Comment by Robdel12** [comment]
I plan on tackling this sometime this week, but I don't think 3.0.0 will be cut until mid july. I wouldn't mind a config option to turn it off in 2.x.

**Comment by Robdel12** [comment]
Merged into 3.0.0 with #139
