### ISSUE TITLE
How does this work with `fillIn` test helper?

### ISSUE THREAD

**Issue by seanpdoyle** [thefrontside/emberx-select#13]
Since the `fillIn` API uses jQuery under the hood, how will tests select values?

Instead of controlling the `optionValuePath` (i.e. `content.id`), the addon manages that for us by referring to the model's Ember ID (i.e. `"<my-app@model:post::ember621:1>"`).

How could we select the proper `<option>`, given that calling `fillIn` with the text value doesn't seem to work?

**Comment by cowboyd** [comment]
What we've been doing is two lines

```
$('.spec-x-select').prop('selectedIndex', 0).trigger('change')
```

**Comment by seanpdoyle** [comment]
@cowboyd with `0` being the index you'd want to select, and `.spec-x-select` being the selector?

How could we write an async helper to find the option and its index?

**Comment by fivetanley** [comment]
Maybe something like:

```javascript
Ember.Test.registerAsyncHelper('selectIndex', function(app, selector, index) {
  var $selectBox = findWithAssert(selector);
  Ember.run(function(){
    $selectBox.prop('selectedIndex', 0).trigger('change');
  });
  return wait();
});
```

? Might be far off here.

**Comment by seanpdoyle** [comment]
I think what I'm getting at is that knowing the 0-based index of an option is less than ideal.

What do we think is a better approach? Fixing the library to inter-op with the standard test helpers, or including an async test helper with the library? 

I'm open to taking a stab at either.

**Comment by cowboyd** [comment]
You might could use the jquery `contains` selector to make an async helper to select a particular option. To riff on @fivetanley's implementation:

```js
Ember.Test.registerAsyncHelper('select', function(app, selector, text) {
  findWithAssert(`${selector} option:contains(${text})`).each(function() {
    Ember.run(this, function() {
      this.selected = true;
      $(this).trigger('change')
    })
  })
  return wait();
});
```

Then it would be invoked like so:

```js
select('.selector-to-select-box', 'Text in Text box')
```

We could could probably just run it as an index if the second argument is a number instead of a string.

I haven't tried this out or anything, but it should theoretically work.
