### ISSUE TITLE
Is it possible to make updating disabled on an option reset the selected option?

### ISSUE THREAD

**Issue by jameshoward** [thefrontside/emberx-select#136]
This is a bit of an edge case but I'm wondering it it's possible, maybe by extending x-select.

I have linked select boxes where picking an option in select 1 changes the available options in select 2. It is useful to still be able to see the other options so I'm using `disabled=true` on the `xs.option` when I don't want it to be selectable.

The issue arises where the 2nd select is set to a value then the 1st select is changed in a way that means the 2nd select's value is now disabled. Basically, the selected option is now also disabled, which is an invalid state in my case.

I think what I need is that when the option's disabled state changes and it is the currently selected value for the select's value to change to the first non-disabled option. Trouble is that I can't work out a sensible way to do this, especially when trying to avoid observers, so any thoughts would be appreciated.

**Comment by Robdel12** [comment]
Hi @jameshoward! Thanks for taking the time to open an issue.

Can you post a code example, maybe a twiddle, showing what you're working with? I have a feeling you're fighting 2 way data binding right now :)

**Comment by jameshoward** [comment]
I wondered about data binding too but I believe it might actually be simpler.

Here's an example: https://ember-twiddle.com/237bcae7e8929d4b7e0e418792d5f06e?openFiles=templates.application.hbs%2C

There are a set of options defined in the controller. To start with, A and C are disabled. As makes sense, B is automatically picked by x-select. However, if the disabled property of the `x-option` is changed later, the select remains in an invalid state as B is still selected despite it now being disabled. If you click it to see the dropdown, the options are correctly marked as disabled.

I think what I need is a way to make it so that if the selected option becomes disabled, re-select the first option that isn't disabled.

Hope it makes more sense with the code example.

**Comment by cowboyd** [comment]
What if we fired an action whenever an option became disabled?

```hbs
{{#x-select as |select|}}
  {{#select.option on-disable=(action "checkValiditiy")}}Hello{{/select.option}}
{{/x-select}}
```

**Comment by jameshoward** [comment]
Yeah that could work, I can then manually switch to the first non-disabled option.

**Comment by Robdel12** [comment]
We could totally add this to v3.0.0, so I'll tag it 👍
