### ISSUE TITLE
Misleading docs?

### ISSUE THREAD

**Issue by k3n** [thefrontside/emberx-select#156]
### Version of x-select:

2.2.2

The docs tell me that for testing, I can just pull in `select()` from `helpers/x-select`, and yet that file isn't included in the latest release.

Was this intentional? When do you expect to release a version with the new test-helper?

Thank you.

**Comment by Robdel12** [comment]
That's correct, we haven't released 3.0 right now and that's currently on master. I hope to get it buttoned up over the next week!

**Comment by k3n** [comment]
Sounds good, thanks!
