### ISSUE TITLE
Bug with computed properties

### ISSUE THREAD

**Issue by JackEllis** [thefrontside/emberx-select#158]
So this here: http://thefrontside.github.io/emberx-select/#/default-value works fine...

But if I had 2 selects (Country & City)... If I changed Country, and I had a computed property called 'filteredCities' which was used in an {{#each}} for the City dropdown, it would throw an error:

> DEPRECATION: You modified selected twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 3.0 [deprecation id: ember-views.render-double-modify]

I'm not sure why it's doing this. When attempting to do {{#if index}} to set set selected=true (like on the test here: http://thefrontside.github.io/emberx-select/#/default-value) it works okay but cannot handle blank values.

I'm wondering if anyone else is experiencing this? It's not the end of the world because my app still works but it's deprecated and I'm pretty confident this is an x-select bug...

The problem is in x-option.js on the selected computed property. If I have the computed property 'update' but return the same value, I don't get the issue. If it changes, it runs the selected computed property on x-option twice.

I believe the problem comes because the options are changing and then the binded value is changing each time because the city that WAS selected is no longer there.

**Comment by bmass02** [comment]
@JackEllis I have experienced the same thing, but after looking through the master branch, I believe the fix has already been made and just hasn't been released. Since version 2.2.2, the _setDefaultValues method has been wrapped in an Ember.run.once. I can't be for certain this fixes it because I didn't use master to confirm. However, I did wrap _updateValue and _setDefaultValues (of version 2.2.2) in Ember.run.once which fixed the issue (for my specific instance).

**Comment by JackEllis** [comment]
@bmass02 Bang on. That fixes it. I've submitted a PR

**Comment by bmass02** [comment]
@Robdel12 Do you have a relative date when the next release will be? Here is the commit that I believe to have already solved this issue [coalesce registering and unregistering options](https://github.com/thefrontside/emberx-select/commit/9e4f8712f66a83e8cc85f196be25c2eac9903ee4). Thanks in advance.

**Comment by Robdel12** [comment]
should be closed with #173 and released with v2.2.3
