### ISSUE TITLE
Binding options

### ISSUE THREAD

**Issue by ultimatemonty** [thefrontside/emberx-select#16]
Is it possible to bind the options? I tried `{{x-select value=condition.subject options=selectOptions action="selectSubject"}}` where `selectOptions` is an array of objects with no success. I didn't see in the tests or code where it was or wasn't possible so figured I'd ask.

Thanks!

**Comment by cowboyd** [comment]
Not currently, you need to have an `each` where you enumerate the options. There is a PR #8 which let's you use a more `Ember.SelectView` style syntax which hopefully will get merged soon.

**Comment by ultimatemonty** [comment]
OK cool. Thanks for answering!
