### ISSUE TITLE
Demonstration deployment seems broken

### ISSUE THREAD

**Issue by backspace** [thefrontside/emberx-select#168]
Hello! Thanks for all your work in creating and maintaining this library.

I’m looking into a possible Edge bug that I may report later, but in the course of my diagnosis, I’ve noticed that your [demonstration](https://emberx-select.pagefrontapp.com/single) seems broken; I’d expect given the [template](https://github.com/thefrontside/emberx-select/blob/fc7fdba978c114182937919d63dfd5d1e7f0a1ae/tests/dummy/app/templates/single.hbs) that the “single” route would have a `<select>` with four options, but only the non-contextual component one is showing… 🤔

**Comment by Robdel12** [comment]
I'm going to close this since the demo page is very different now :)
