### ISSUE TITLE
Backport ember-source npm package

### ISSUE THREAD

**Issue by efx** [thefrontside/emberx-select#178]
https://github.com/thefrontside/emberx-select/commit/05f0c947d321ca59e58cf1213a9552b888ca0201
### Version of x-select:
2.2.1
### Ember Version / Ember CLI Version:

**Ember Version:**
2.11.0 
**Ember CLI Version:**
2.11
### Expected Behavior
I expect the npm install in my project to work.

### Actual Behavior
``` 
$ ember build
DEPRECATION: Putting the "includePolyfill" option in "babel" is deprecated, please put it in "ember-cli-babel" instead.
Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
node_modules/emberx-select/index.js:14:25
    at Array.filter (native)
```

### Steps To Reproduce:
1. create a project with emberx-select@2.2.1 as an entry in `devDependencies`
2. run npm install and bower install
3. run ember build

**Comment by jpadilla** [comment]
Just ran into this as well.

**Comment by Robdel12** [comment]
Are there reasons upgrading to x-select 3.x isn't feasible? 

I honestly have no desire to back port and cut another 2.x release. But I could be convinced if enough people want it.

**Comment by efx** [comment]
@Robdel12 , honestly I would do that but I don't have the resources to dedicate to refactoring components in our application that rely upon behavior of 2.x. I'd be happy with a temporary branch until I can refactor.

**Comment by efx** [comment]
closing the issue as forking and backporting is a good enough fix for now: https://github.com/efx/emberx-select/tree/backported-version-fix.

**Comment by Robdel12** [comment]
Very nice! Thanks :)
