### ISSUE TITLE
How to pass html data attributes to x select component?

### ISSUE THREAD

**Issue by meliborn** [thefrontside/emberx-select#179]

**Comment by Robdel12** [comment]
Hm, this seems to be a weakness in Ember. If you want to add custom data attributes you'll have to reopen the x-select class and add the attributes you want. [Example from the guides](https://guides.emberjs.com/v2.5.0/templates/binding-element-attributes/#toc_adding-data-attributes)

I'm going to close this but feel free to keep commenting! I'll be around to help :)
