### ISSUE TITLE
test against canary

### ISSUE THREAD

**Issue by stefanpenner** [thefrontside/emberx-select#18]
new ember-addons ship with a travis.yml that does this automatically. This would likely be great for this add-on

**Comment by Robdel12** [comment]
I'm trying to get there! :) I have an upgrade branch running but encountered that ember form bug that we talked about yesterday.

**Comment by stefanpenner** [comment]
@Robdel12 i have a-few moments. I am going to try and upgrade this addon to the latest ember-cli. Seems like it is still at 0.1.15

**Comment by Robdel12** [comment]
Awesome! :D

**Comment by Robdel12** [comment]
#40 takes care of this
