### ISSUE TITLE
arguments passed to didReceiveAttrs trigger deprecation in Ember 2.12

### ISSUE THREAD

**Issue by Dhaulagiri** [thefrontside/emberx-select#181]
### Version of x-select:
master

### Ember Version / Ember CLI Version:

**Ember Version:** 2.12.0-beta.3

### Expected Behavior

No deprecation

### Actual Behavior

Deprecation

### Steps To Reproduce:
[This line](https://github.com/thefrontside/emberx-select/blob/ff0eaa42f8bb808178fdbd6dc896d23174dcec11/addon/components/x-option.js#L48) triggers a [deprecation](http://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks) beginning in ember 2.12

**Comment by Robdel12** [comment]
Closed with #186

**Comment by JoshSmith** [comment]
@Robdel12 any chance that we could cut a release to `npm` for this change? Thanks!

**Comment by Robdel12** [comment]
Yeah np! Just cut a new one

**Comment by JoshSmith** [comment]
@Robdel12 just a heads up, but it looks like this wasn't published to `npm` yet.

**Comment by Robdel12** [comment]
So, turns out `npm publush` isn't valid. Should be up now 😅

**Comment by JoshSmith** [comment]
Haha! Come on npm! Where's the obvious alias?

**Comment by JoshSmith** [comment]
Got it all updated! Thanks again for pushing this.

**Comment by Robdel12** [comment]
Woop! Happy to help :)
