### ISSUE TITLE
Set ember-try ember#release back

### ISSUE THREAD

**Issue by Robdel12** [thefrontside/emberx-select#184]
For some reason when I was upgrading ember-cli to 2.12 ember#release (which is 2.12 currently) was totally broken (77 failing tests). But if I install ember 2.12 the tagged version everything is fine. 

This makes me think something about ember#release is broken. Especially because ember#beta passed all the tests. 

(Introduced in #183)

**Comment by Dhaulagiri** [comment]
Noticed this also trying to update things in https://github.com/thefrontside/emberx-select/pull/195.  It's puzzling since things seemed to work locally trying that configuration but obviously something is not happy when run in travis.

**Comment by Robdel12** [comment]
This will be closed in with #203.

**Comment by Robdel12** [comment]
This can be closed since #203 was merged
