### ISSUE TITLE
Test Helper Fails To Find Select Element

### ISSUE THREAD

**Issue by krazylegz** [thefrontside/emberx-select#188]
### Ember Version / Ember CLI Version: 3.0.1

**Ember Version:** 2.12.0
**Ember CLI Version:** 2.12.1

### Expected Behavior

The `select` test helper should be able to find the element when given the selector, and the test should pass.

### Actual Behavior

The `select` test helper cannot find the select. It reports that it could not find any options in the select. https://gist.github.com/krazylegz/355ae971a8734b28337efb4e51c66b95

### Steps To Reproduce:
1. Use the `select`helper in a test configured to pass.
2. Run `ember test`.

### Ember Twiddle / Example repo / Failing test: https://github.com/krazylegz/emberx-select-test

_Please create a reproduction of your [bug with this ember-twiddle](https://ember-twiddle.com/7e9d38ee074b00b40c7d2aee83ebb9ae). This is extremely helpful and speeds up the debugging process._

**Comment by Robdel12** [comment]
Thanks for the issue & example repo! It looks like the example the select isn't rendered yet, so it can't select anything from it. 

![not rendered select](https://cloud.githubusercontent.com/assets/2072894/24559389/15d7950c-1604-11e7-9c6a-88a399a521b2.png)

So this did raise the fact that the helper isn't throwing an error like it should be. So I'll get a PR up to fix that. 

I was able to get the tests to pass by moving the select helper down into the `andThen`. 
![image](https://cloud.githubusercontent.com/assets/2072894/24559570/d30da54e-1604-11e7-8883-03dc53be587f.png)
