### ISSUE TITLE
Readme error?

### ISSUE THREAD

**Issue by carrotalan** [thefrontside/emberx-select#197]
### Expected Behavior

The readme describes how to use an action in the route to receive the selected item. 

### Actual Behavior

Closure actions do not bubble up to the route so this example does not work. It either needs to show it working in a component or using something like ember-route-action-helper

### Steps To Reproduce:
1. Read readme

**Comment by Robdel12** [comment]
Woops, you're right! I'm going to change it over to a controller to avoid confusion.
