### ISSUE TITLE
Selection not set when using a RecordArray as `content` and a PromiseObject as `value`

### ISSUE THREAD

**Issue by mphasize** [thefrontside/emberx-select#20]
I'm trying to build a select box to let the user choose a models.belongsTo property from a list of models retrieved through the store. While the selection process in general is working, the initial selection after reloading the page is not set.

`x-select content=recordArray selection=model.belongsToRecord optionValuePath="content" optionLabelPath="content.title"`

If I use `recordArray.content` and `model.belongsToRecord.content`, the initial selection is set properly, but the selection process stops working ( the model.belongsToRecord is not properly set anymore ).

Digging in with the Ember Inspector I can see that the value on the `x-select` component is a `PromiseObject` whereas the value of the `x-option` component is the resolved value of the Promise. 

I guess the comparison between those two with an `===` operator is not working.

**Comment by masciugo** [comment]
Same problem here, but calling `content` solved the initial selection problem keeping, as opposed to  @mphasize, selection process working.

    {{#x-select value=model.belongsToRecord.content action="selectAction"}}
      {{#each recordArray as |item|}}
        {{#x-option value=item}}{{item.name}}{{/x-option}}
      {{/each}}
    {{/x-select}}
