### ISSUE TITLE
Deprecation warning in Ember 2.18.0

### ISSUE THREAD

**Issue by krukid** [thefrontside/emberx-select#205]
### Version of x-select:

3.1.0

### Ember Version / Ember CLI Version:

**Ember Version:** 2.18.0
**Ember CLI Version:** 2.18.1

### Expected Behavior

No deprecation warnings should be shown.

### Actual Behavior

DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/usr/src/dev/node_modules/emberx-select/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)

### Related issue:

https://github.com/ember-cli/ember-cli-version-checker/issues/48

**Comment by Robdel12** [comment]
Thanks for the issue! This should be fixed in `3.1.1`.
