### ISSUE TITLE
Obligatory "doesn't work on Canary issue"

### ISSUE THREAD

**Issue by mitchlloyd** [thefrontside/emberx-select#22]
I tried upgrading an app to the latest Ember build today and I noticed that the `x-select` components weren't rendering anything. I ran the tests in this repo against Canary and it looks like ~~they all fail~~ each module has failing assertions (except for JSHint! :tada:).

I'm sure there's nothing wrong on your end. You guys are great. But those Ember core people... :wink:  Maybe there is an issue that could be filed before 1.13 is out the door or maybe there is [an open issue](https://github.com/emberjs/ember.js/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.13.0) that might be affecting `x-select`?

**Comment by mitchlloyd** [comment]
I think this is the related issue https://github.com/emberjs/ember.js/issues/11301.

**Comment by Robdel12** [comment]
I've briefly looked at the fails on canary but haven't taken the time to troubleshoot. X-select is technically "broken" on anything 1.11+. That's due to this: https://github.com/emberjs/ember.js/issues/11221

I'll take a look and see if it's on our end or not *hopefully* today :)

**Comment by jamesarosen** [comment]
https://github.com/thefrontside/emberx-select/pull/33 has tests passing on Glimmer, though without support for the `form` attribute.

**Comment by Robdel12** [comment]
Closing this. #40 has passing tests on canary :)
