### ISSUE TITLE
<xSelect> is not a component and doesn't support block parameters

### ISSUE THREAD

**Issue by gzurbach** [thefrontside/emberx-select#235]
### Ember Version / Ember CLI Version:

**Ember Version:** 2.18.0
**Ember CLI Version:** 2.18.2

### Expected Behavior

The documentation should provide working examples.

### Actual Behavior

After installing the addon and copy-pasting the example in docs, which is:
```hbs
<XSelect @value={{bob}} @onChange={{action 'selectPerson'}} as |xs|>
  <xs.option @value={{fred}}>Fred Flintstone</xs.option>
  <xs.option @value={{bob}}>Bob Newhart</xs.option>
</XSelect>
```
I then got this error upon build:
```
Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in webapp/templates/foo.hbs

Compile Error: <xSelect> is not a component and doesn't support block parameters
```
I was able to make it work by changing it to:
```hbs
{{#x-select value="bob" on-change=(action 'selectPerson')}}
  {{#x-option value="fred"}}Fred Flintstone{{/x-option}}
  {{#x-option value="bob"}}Bob Newhart{{/x-option}}
{{/x-select}}
```
I might be missing something since I am not using the latest version of Ember, but maybe the docs should be updated to indicate the valid syntax for older versions?

### Steps To Reproduce:
1. `ember install emberx-select`
2. Copy-paste basic example from docs
3. `npm start`

**Comment by backspace** [comment]
It’s true that you need Ember 3.4 to be able to use angle-bracket components. You could use [this polyfill](https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill) to have it with your Ember version. It does seem like the documentation should mention this requirement, want to make a pull request?

**Comment by gzurbach** [comment]
Done. See https://github.com/thefrontside/emberx-select/pull/236. Cheers!
