### ISSUE TITLE
action not fired when expected

### ISSUE THREAD

**Issue by optikalefx** [thefrontside/emberx-select#36]
Using this for the first time.

given this example

```
{{#x-select id="age-group" value=ageGroup action="selectAgeGroup"}}
	{{#x-option}}Select Age Group...{{/x-option}}
	{{#x-option value="18-25"}}18-25{{/x-option}}
	{{#x-option value="25-35"}}25-35{{/x-option}}
	{{#x-option value="35-55"}}35-55{{/x-option}}
	{{#x-option value="55+"}}55+{{/x-option}}
{{/x-select}}
```

when action is fired, it receives the previous value. So if I change to "25-35" from "18-25". `this.get("ageGroup")` is 18-25. Not the new value.

The only way I can get this to work is to use an observer. That has the correct value.

**Comment by Robdel12** [comment]
I'm going to close this because I can't replicated on current master. If this comes up again I'll reopen :)
