### ISSUE TITLE
Depreciation - Performance degradation

### ISSUE THREAD

**Issue by mnowik** [thefrontside/emberx-select#46]
A depreciation is trigger:
*You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation.*

It is caused by addon/components/x-option.js (line 60) in the didInsertElement:

``` this.set('select', select); ```

Any way to find a better solution ?

**Comment by cowboyd** [comment]
We could probably compute it.

**Comment by Robdel12** [comment]
Are you using 1.1.3 or 1.1.4? The two issues you made today were fixed but not released yet :)

Try using master: `"emberx-select": "thefrontside/emberx-select#master`. That should fix ya up!

**Comment by mnowik** [comment]
Sorry for the delay, I am using 1.1.4. 
Ok, I will try to use ```master```
