### ISSUE TITLE
Multiple {{x-selects}} on the same template

### ISSUE THREAD

**Issue by shamanime** [thefrontside/emberx-select#48]
I am trying to use multiple selects on my template, as follows:

```handlebars
<label>Type</label>
{{#x-select value=model.type.content action="selectType"}}
  {{#each types as |item|}}
    {{#x-option value=item}}{{item.name}}{{/x-option}}
  {{/each}}
{{/x-select}}
<label>Status</label>
{{#x-select value=model.status.content action="selectStatus"}}
  {{#each statuses as |item|}}
    {{#x-option value=item}}{{item.name}}{{/x-option}}
  {{/each}}
{{/x-select}}
```

But this throws the following message in the console:
```
Error: Assertion Failed: x-option component declared without enclosing x-select
```

If I remove either of the selects, it works.

The relevant route code:

```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  setupController: function(controller, model) {
    this._super(controller, model);

    controller.set('statuses', this.store.findAll('status'));
    controller.set('types', this.store.findAll('type'));
  },

  actions: {
    selectStatus: function(selection) {
      console.log('Selecting status');
      if (selection) {
        this.get('currentModel').set('status', selection);
      }
    },

    selectType: function(selection) {
      console.log('Selecting type');
      if (selection) {
        this.get('currentModel').set('type', selection);
      }
    }
  }
});
```

Am I doing something wrong?

PS: Using version 1.1.4, ember-cli 1.13.1.

**Comment by jcope2013** [comment]
i have got multiple ones working but was seeing something similar when i had two until i got it working, it seemed async related so i switched some stuff around.

these may clear it up

https://github.com/thefrontside/emberx-select/issues/44
https://github.com/thefrontside/emberx-select/pull/45

**Comment by Robdel12** [comment]
I'm curious: if you just upgrade ember to 1.13.4, does that fix it?

I really need to finish this blog post. There a couple ember bugs that make using this addon a little less reliable.

**Comment by shamanime** [comment]
@Robdel12 oh, it did work with Ember 1.13.4 (forgot to say that it was 1.13.3 previously) on both master and 1.1.4.

Works like a charm now. I should have tried this before creating the issue.

Thank you!

**Comment by Robdel12** [comment]
@shamanime Awesome! Glad that worked :D
