### ISSUE TITLE
Disable x-select mutating "value" upon selection

### ISSUE THREAD

**Issue by engwan** [thefrontside/emberx-select#52]
Should we add a way to disable the mutating behavior of x-select? I want to trigger the action only and leave the value as-is.

I was surprised the component did this as it violates ember's "data down actions up" principle.

We can actually just remove the mutating behavior, and if you want to mutate the value, you can easily pass in an action with the `mut` helper.

Something like:

    {{#x-select value=currentSelection action=(action (mut currentSelection))}}
      ....
    {{/x-select}}

**Comment by Robdel12** [comment]
I know @cowboyd has had it in the plan for 2.0 to make the value array immutable.

**Comment by cowboyd** [comment]
There are two things to consider 

1) the binding of the "value" property
2) mutability of the collection in the case that it is bound to the collection.

For the first case, `x-select` will just follow the default behavior of whichever ember version/syntax you happen to be using, so `{{x-select value=currentSelection}}` and `<x-select value={{mut currentSelection}}>` will be two-way, but `<x-select value=currentSelection>` will be one-way.

In the case of multiple values, emberx-select 2.0 will never mutate collections in place, and will always treat them as immutable.

**Comment by Robdel12** [comment]
This probably has been addressed with: https://github.com/thefrontside/emberx-select/commit/851031771cff143deea21b9094669d93a4d8435e

Can you give a try and let us know?
