### ISSUE TITLE
Selection not selected when component rerendered

### ISSUE THREAD

**Issue by knownasilya** [thefrontside/emberx-select#54]
```hbs
{{x-select content=baseThemes
  action="changeBaseTheme"
  selection=currentBaseTheme
  optionLabelPath='content.label'
  optionValuePath='content.id'}}
```

When the action fires, it sets `currentBaseTheme` which is located in a service. Now this select is in a panel that renders in an outlet. Once the panel is closed, and reopened, even though `currentBaseTheme` is the last selected value, the select box shows the first option as selected.

**Comment by knownasilya** [comment]
I think that this https://github.com/thefrontside/emberx-select/blob/master/addon/components/x-select.js#L181 should default to `this.get('value')`.

**Comment by krivaten** [comment]
:+1: Having this same problem.

**Comment by dknutsen** [comment]
I'm also having an issue with this, specifically when using query params I set a value on my controller property that the x-select is bound to ('user' in this case) and I can see that the controller definitely has 'user' set on it but the x-select does not display it. If I select an item the query param updates, just not the other way around.

**Comment by Robdel12** [comment]
Closing this since this seems to be related to the blockless select.
