### ISSUE TITLE
emberx-select does not select initial value in component

### ISSUE THREAD

**Issue by jackmatt2** [thefrontside/emberx-select#56]
I have a component whereby I inject a `site` ember-data model into it.

Using `Ember.Select` the following is working
```javascript
                    {{view "select"
                    class="form-control"
                    content=sites
                    optionValuePath="content.id"
                    optionLabelPath="content.displayName"
                    selection=site
                    disabled=false
                    prompt="Please Select"
                    }}
```

I have converted it to emberx-select as follows
```javascript
                    {{site.name}} <!-- This correctly displays the site name -->
                    {{log site}}
                    {{#x-select disabled=false value=site action=(action (mut site)) class="form-control"}}
                      {{#x-option value=null}}Please Select{{/x-option}}
                      {{#each sites as |item|}}
                        {{#x-option value=item}}
                          {{item.displayName}}
                        {{/x-option}}
                      {{/each}}
                    {{/x-select}}
```

But the selected item remains on "Please Select" when the page is refreshed.  As the site is `{{async:true}}` in the parent model `model.site` I have tried using `value=site.content` but that does not work either.

Any ideas?

**Comment by cowboyd** [comment]
Sorry you're experiencing this issue. My guess is that site is a PromiseProxy, so you will need to put `value=site.content` on both the `x-select` component and also each `x-option`

**Comment by Robdel12** [comment]
I'm going to close this, but if it's not solved feel free to comment and we'll reinvestigate and reopen :)

**Comment by JackEllis** [comment]
I know this was closed over a year ago but for anyone coming here from having their own problems, updating to to 2.2.2 fixed the issue of the select boxes setting the binded value to NULL!
