### ISSUE TITLE
Blockless and block form do not behave the same.

### ISSUE THREAD

**Issue by jackmatt2** [thefrontside/emberx-select#59]
The following two controls are essentially the same.  The problem is that the BLOCKLESS control does not set the initial selection property via ` selection=addressType`; it remains on the first option.  It work perfectly in the BLOCK control using ` value=addressType`. 

BLOCKLESS
```javascript
                      {{x-select action=(action (mut addressType))
                      multiple=false
                      content=addressTypes
                      selection=addressType
                      optionValuePath="content.id"
                      optionLabelPath="content.name"
                      }}
```

BLOCK
```javascript
                    {{#x-select value=addressType action=(action (mut addressType)) }}
                      {{#each addressTypes as |item|}}
                        {{#x-option value=item.id}}
                          {{item.name}}
                        {{/x-option}}
                      {{/each}}
                    {{/x-select}}
```

In my controller
```javascript
  addressTypes : [
    {
      id : 'PRIVATE',
      name : 'Private Address'
    },{
      id : 'BUSINESS',
      name : 'Business Address'
    }
  ],
```

**Comment by cowboyd** [comment]
Indeed, the code-paths diverge significantly between BLOCK and BLOCKLESS forms. We added the blockless form to act as a bridge for migrating from `Ember.Select`. However, we do not recommend it. In fact, it will be removed from `x-select` 2.0 and extracted to a plugin.

Work has begun already on this: https://github.com/thefrontside/emberx-select-blockless

My recommendation is to use the block form. It can feel verbose at times, but it has been our experience that less magic is more.
