### ISSUE TITLE
Matching selected value on related records via async

### ISSUE THREAD

**Issue by gte451f** [thefrontside/emberx-select#68]
I've been trying to learn x-select and ran across some odd behaviour I'd like to ask about.  Basically records from my api *related via async:*  **true** are recognized with it's matching record.  When I flip the switch and say async: false, the matching records are recognized.  

The record loaded through an async:true relationship is wrapped up in a promise object.  This happens even when records are eager loaded from the api.

So how can I compare related records when they are wrapped up in a promise object?

Here is a contrived example:

> models/city.js
```javascript
export default DS.Model.extend({
    ...
    state: DS.belongsTo('state', {async: true}),    
    //false means the matching value is detected in subsequent x-select    
});
```
> city.state is different depending on async:true|false
> consequently it doesn't match up correctly
```htmlbars
            {{#x-select value=city.state}}
                {{#x-option value=null}}Select{{/x-option}}
                {{#each states as |item|}}
                    {{#x-option value=item}}{{item.id}}{{/x-option}}
                {{/each}}
            {{/x-select}}
```

**Comment by jcope2013** [comment]
try this

``` {{#x-select value=city.state.content}} ```

https://github.com/thefrontside/emberx-select/issues/20

**Comment by gte451f** [comment]
You are correct sir!
