### ISSUE TITLE
Issues with promise values?

### ISSUE THREAD

**Issue by drapergeek** [thefrontside/emberx-select#69]
I'm trying to use this addon with a select value that is a promise. It seems that the `===` check here: https://github.com/thefrontside/emberx-select/blob/master/addon/components/x-option.js#L45 will not return true if the `select.value` is actually a promise object, even though the values are "equal". I've solved this locally by sending over the `value.content` if there is a content property. This leads to a lot of strange behaviors unfortunately.

Is this a problem others are seeing or am I doing something weird? Happy to put in a PR to fix this if this is an actual issue.

**Comment by cowboyd** [comment]
you'll need to use the `.content` property for both the select value and the option value for this to work. We could also use `Ember.isEqual` to do the comparison, but you would have to make sure that your promise objects actually implemented that method.

**Comment by drapergeek** [comment]
Thanks for the reply. I attempted to use the `.content` but then when it tries to set back to that value it became an issue.

I also tried going into the source and using `isEqual`but it doesn't look like native promises have this function set.

Would a PR that will check for a promise and unpack it make sense?

**Comment by robclancy** [comment]
This issue is a pretty big one...

**Comment by peec** [comment]
I originally had the same issue, I solved it using content and action together.

```js
     // controller:
  actions: {
    selectCategory(category) {
      this.get('model').set('category', category);
    }
  },
```

```handlebars
{{#x-select class="form-control" value=model.category.content action="selectCategory"}}
    <option value="No category"></option>
    {{#each product_categories as |category|}}
        {{#x-option value=category}}{{category.name}}{{/x-option}}
     {{/each}}
{{/x-select}}
```

**Comment by miguelcobain** [comment]
@peec's example can be shortened using the new `mut` and `action` helper:

```hbs
{{#x-select value=model.category.content action=(action (mut model.category))}}
    <option value="No category"></option>
    {{#each product_categories as |category|}}
        {{#x-option value=category}}{{category.name}}{{/x-option}}
     {{/each}}
{{/x-select}}
```

`mut` returns a mutable object for the passed in property.
the `action` helper is smart enough to return a function that mutates the passed in mutable object.
This seems to be currently working with Ember Data promises.

**Comment by mattmcginnis** [comment]
Here's what worked for me:


```js
//app/validators/belongstomodel.js
import Ember from 'ember';
import Base from 'ember-validations/validators/base';

export default Base.extend({
  call: function() {
    var propertyName = this.property,
        attributeName = propertyName.replace('model.', '').underscore().replace(/_/g, ' ').capitalize(),
        controller = this.model,
        property = controller.get(property);

    if (property && Ember.isEmpty(property.get('content'))) {
      this.errors.pushObject(attributeName + " cannot be blank");
    }
  }
});
```

```js
 // Controller
 validations: 
    'model.something': {
      belongstomodel: true
    }
  },

  actions: {
    selectSomething(something) {
      this.get('model').set('something', something);
    }
  },
```

```hbs
  <!-- Template -->
  {{#x-select value=model.something.content action="selectSomething"}}
    {{#x-option value=""}}
      Select a something
    {{/x-option}}
    {{#each somethings as |something|}}
      {{#x-option value=something}}
        {{something.name}}
      {{/x-option}}
    {{/each}}
  {{/x-select}}

```

**Comment by gordonbisnor** [comment]
@miguelcobain thanks this solution worked well

**Comment by cowboyd** [comment]
Indeed, the solutions proffered by @peec and @miguelcobain are the way DDAU is supposed to work. Thanks guys!

**Comment by brisc** [comment]
The DDAU example should be added to the documentation.
