### ISSUE TITLE
x-option registers too often

### ISSUE THREAD

**Issue by arunasf** [thefrontside/emberx-select#70]
x-option component tries to register itself from didRender() hook (https://github.com/thefrontside/emberx-select/blob/master/addon/components/x-option.js#L54). And didRender() hook is called on every re-render cycle (http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_component-lifecycle-hooks).
Sometimes in acceptance tests we get into situations then x-option tries to register itself after outer x-select is removed (naturally an exception is thrown).

I think it is not necessary to register from every didRender call and it should be enough from didInsertElement() hook.

**Comment by cowboyd** [comment]
I agree. We were actually doing this before, but hitting a deprecation. 

I agree that this only needs to happen once on initial render, and so despite the deprecation, `didInsertElement` seems like the natural place for it.  The solution proposed [here](https://github.com/emberjs/ember.js/issues/11493#issuecomment-113013866), could work, but we'd still be triggering a re-render which I assume is the "significant performance degradation" that the deprecation is warning about. The only difference would be that the warning is hidden... Seems less than ideal, but the Right Way&#8482;, if there is one, isn't clear to me.

**Comment by arunasf** [comment]
I just checked ```didInsertElement``` hook in Ember 2.0.0 sources. It's not marked as deprecated (although View is deprecated). 
But from ember component tests looks like only *changing a component's displayed properties inside ```didInsertElement()``` is deprecated*. And you do not change any properties, you just schedule x-option's registration in the run-loop.

Also I tried changing ```didRender``` to ```didInsertElement``` and it did not generate any new deprecation messages to console (using Ember 2.0.0).

So i think it quite safe to use ```didInsertElement```, at least until Ember 3.0.

**Comment by cowboyd** [comment]
Oops, I was not suggesting that `didInsertElement` is deprecated, only that setting properties inside it is. 

However, you're right, it looks like we not only changed it do `didRender`, but we also added it to run in the `afterRender` queue. Can you submit the PR, so that we can release it as 2.0.1?

**Comment by Robdel12** [comment]
This was fixed in 2.0.1.
