### ISSUE TITLE
Is it possible to set a default value?

### ISSUE THREAD

**Issue by ismay** [thefrontside/emberx-select#78]
I'm currently doing this to preselect the default value:

```
{{#x-select value=currentSelection}}
  {{#each model.persons as |person|}}
    {{#if person.default }}
    {{#x-option value=person.id selected=true}}
      {{ person.name }}
    {{/x-option}}
    {{else}}
    {{#x-option value=person.id }}
      {{ person.name }}
    {{/x-option}}
    {{/if}}
  {{/each}}
{{/x-select}}
```

But this doesn't set `currentSelection` when rendered (even though it does show the default as selected). `currentSelection` is only set after manually selecting a value. Couldn't find anything about this in the docs. Is there a recommended way of doing this with emberx-select?

**Comment by cowboyd** [comment]
unrelated, but I  think you could simplify your template like so.

```handlebars
{{#x-select value=currentSelection}}
  {{#each model.persons as |person|}}
    {{#x-option value=person.id selected=person.default}}
      {{ person.name }}
    {{/x-option}}
  {{/each}}
{{/x-select}}
```
It sounds like you're wanting it to immediately update `value` as soon as an option is marked as selected? I'd have to think about it, and we may go that route.

An alternative in the mean time is to initialize `currentSelection` in your controller to your default value if it is null.

**Comment by ismay** [comment]
> unrelated, but I think you could simplify your template like so.

Ah yes of course. Thanks.

> It sounds like you're wanting it to immediately update value as soon as an option is marked as selected?

If that would also trigger on rendering then yes I'm all for it. 

> An alternative in the mean time is to initialize currentSelection in your controller to your default value if it is null.

Thanks. In the meantime that'll be a good solution, but in the long run it'd be good for this to be possible without the use of a controller (because of their upcoming deprecation).

**Comment by cowboyd** [comment]
Instead of controller, I should have said "enclosing scope" your routable component would have this property going forward.

**Comment by ismay** [comment]
Ah ok.

**Comment by Robdel12** [comment]
Looks like this was taken care of. Feel free to reopen/comment if that's not the case :)
