### ISSUE TITLE
Any way to attach to blur event?

### ISSUE THREAD

**Issue by csetera** [thefrontside/emberx-select#84]
Is there any way to attach an event handler to the blur event of an x-select?  We are trying to use emberx-select as an "inline" editor that "commits" only on blur, but I can't figure how to attach to arbitrary DOM events as I can with, for instance, with a TextView.  I considered options for extending or "reopening" the x-select component, but I've not found a good way to get a handle on the component to try to make that work.

Suggestions would be greatly appreciated.
Thanks!

**Comment by shreyjairath** [comment]
+1 Trying to do exactly the same thing

**Comment by cowboyd** [comment]
I think we should follow the ember conventions and allow you to have `on-click`, `on-change`, `on-blur`, etc... actions

**Comment by csetera** [comment]
I tried to figure out how to do exactly this, but my Ember component skills are not quite up to that level yet.

**Comment by cowboyd** [comment]
would be something probably like:

```javascript```
blur(event) {

**Comment by cowboyd** [comment]
To clarify, this would be a change to the actual x-select component.

**Comment by csetera** [comment]
This would be awesome.  Any thoughts on when this might be available?

**Comment by Robdel12** [comment]
Absolutely by the 30th :P 

I'm hoping I can get some time this week/weekend to start working on this. 

- [ ]  `on-click` 
- [ ]  `on-change`
- [ ]  `on-blur`

**Comment by csetera** [comment]
This list would meet our needs for sure.  Thanks so much for helping out.

**Comment by Robdel12** [comment]
This has just been merged into master! Give it a shot if you'd like. We should be cutting 2.1 by this weekend (I hope!)

This issue is closed by #92
