### ISSUE TITLE
Remove dead placeholder / prompt param

### ISSUE THREAD

**Issue by stephencattaneo** [thefrontside/emberx-select#85]
the x-select component code has  `placeholder` yet the the template doesn't take advantage of it.

**Comment by Robdel12** [comment]
Good catch. This is actually leftover from when we supported a blockless form of the component. If you still would like to do that you can use [x-select-blockless](https://github.com/thefrontside/emberx-select-blockless).

**Comment by stephencattaneo** [comment]
FWIW this change fixes it (app/templates/components/x-select.hbs):
```
{{#if placeholder}}
  {{#x-option}} {{placeholder}} {{/x-option}}
{{/if}}
{{yield}}
```

**Comment by cowboyd** [comment]
@stephencattaneo 

The philosophy of `x-select` is to be as thin a wrapper around the native select option as possible. That way, it remains simple, flexible, and clear how to work with it given knowledge of the standard `select` and `option` tags.

So would definitely accept a PR to remove the `placeholder` attribute, but not one to use it in the template.
