### ISSUE TITLE
how we can write integration test for x-select?

### ISSUE THREAD

**Issue by vinodhrajamuralidharan** [thefrontside/emberx-select#87]
- [X] -  I am aware of 'select' instead of fillIn in acceptance testing, would like to write integration test for my project.
- [X] -  I tried the helpers as per the doc says and that is not working.
- [X] - currently I am using  'this.$('').prop('selectedIndex', 1).trigger('change');' - do we have any other way around for this?

**Comment by cowboyd** [comment]
What isn't working about the `select` helper?

**Comment by vinodhrajamuralidharan** [comment]
integration test to select a value in the ember for x-select

**Comment by cowboyd** [comment]
Can you post an example of the code you're using that is not working for you?

**Comment by vinodhrajamuralidharan** [comment]
test('Selected value in the box should be displayed', function (assert) {
  var
    mockResponse = {
      data: {
        addresses: addressList
      }
    };
  this.set('request', function () {
    return Ember.RSVP.Promise.resolve(mockResponse);
  });
  this.on('addressProvided', function (address) {
    assert.equal(address, addressList[0].address, 'selected address should be passed');
  });
  this.render(hbs`{{component-name
    postcode='tw183he'
    selectedAddressFromList="selectedAddressFromList"
    request=request
    selectedAddress="addressProvided"}}`);
  this.$('#findAddress').click();
//select('.address-list', addressList[0].address);  -- not working
  this.$('.address-list').prop('selectedIndex', 1).trigger('change');  -- working one
});

**Comment by Robdel12** [comment]
What's `addressList`? In your case `addressList[0].address` should be the rendered text for the select. 

So if `addressList = ['thingy', 'another thingy'];` then your select rendered should look something like:

```html
<select class="address-list">
  <option>thingy</option>
  <option>another thingy</option>
</select> 
```

And the select helper would select it by doing: `select('.address-list', 'thingy');`

**Comment by vinodhrajamuralidharan** [comment]
I tried that, though I added the helpers as per the document, I get error like
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:29:9): select is not defined
But for acceptance test case, it works fine. Only on integration test, I get this error.

**Comment by Robdel12** [comment]
Interesting. I'll have to take a peek in the morning :)

**Comment by Robdel12** [comment]
After doing some digging [it looks like ember](https://github.com/rwjblue/ember-qunit/issues/88#issuecomment-59508186) doesn't _want_ you to use test helpers in integration tests. 

It looks like you're going to need to do it the jQuery way: `this.$('.address-list').prop('selectedIndex', 1).trigger('change');`

**Comment by vinodhrajamuralidharan** [comment]
yes. Actually, I have done this way only. I will also investigate this

**Comment by Robdel12** [comment]
This will be taken care of in #118. So I'm going to close this in favor of that.
