### ISSUE TITLE
dynamically hide options

### ISSUE THREAD

**Issue by Nef10** [thefrontside/emberx-select#98]
I want to hide some options based on the property `isStreak`. So I wrote the following code:

```hbs
{{#x-select value=format}}
  {{#each formats as |format|}}
    {{#x-option value=format}}{{format}}{{/x-option}}
  {{/each}}
  {{#unless isStreak}}
    {{#each buildStatesFormats as |format|}}
      {{#x-option value=format}}{{format}}{{/x-option}}
    {{/each}}
  {{/unless}}
{{/x-select}}
```

This code does show all options regardless of `isStreak`. If I put the whole `x-select` inside an `unless` everything works fine, but this is not what I am looking for.

Is this a bug, or is this just not supposed to work?

 
_Version of x-select: 2.0.2
Ember Version / Ember CLI Version: 2.3.0_

**Comment by Robdel12** [comment]
This sounds very much like a bug. We'll have to investigate what's going on.

**Comment by cowboyd** [comment]
As a workaround, I'd suggest having a computed property that merges the two lists `formats` and `buildStatesFormats` according to the `isStreak` property. That way, you're only eaching over a single list.

**Comment by Robdel12** [comment]
Hey @Nef10! 

I was able to sit down tonight and try to replicate this bug. It looks like this works as it should on master. Could you give master a shot and see if that fixes the issues in your app?

Here's the code that I used to replicate:
- [Controller](https://github.com/thefrontside/emberx-select/blob/sandbox/tests/dummy/app/controllers/sandbox.js#L14)
- [Template](https://github.com/thefrontside/emberx-select/blob/sandbox/tests/dummy/app/templates/sandbox.hbs#L20)
- [Ember try build vs Ember 1.13.0-2.4.0](https://travis-ci.org/thefrontside/emberx-select/builds/114970999)

**Comment by Robdel12** [comment]
I went ahead and decided to investigate further since it's open source and opened a PR implementing what I think you were trying to do :)

https://github.com/HPI-BP2015H/travis-web/pull/1

Going to close this issue.
