### ISSUE TITLE
x-option declared without x-select error

### ISSUE THREAD

**Issue by horacekj** [thefrontside/emberx-select#99]
### Version of x-select:
2.0.2
### Ember Version / Ember CLI Version:
1.13.15
### Problem:

    {{#x-select value=task class="form-control"}}
      {{#x-option value=""}}Všechny úlohy{{/x-option}}
        {{#each tasks as |t|}}
          {{#x-option value=t}}{{t.title}}{{/x-option}}
        {{/each}}
    {{/x-select}}

`tasks` is computed property. When `tasks` changes, browser logs to console: Error: Assertion Failed: x-option component declared without enclosing x-select.

I expect x-option to update its items withnout prompting any error.

### Steps To Reproduce:
Simply declare `tasks` as computed property and template as showed above.

**Comment by Robdel12** [comment]
Thanks! I'll take a look tonight after work :)

**Comment by horacekj** [comment]
Thank you very much :-).

**Comment by horacekj** [comment]
Just a few more info to understand my problem better (and to reproduce it):
My template contains two x-selects. Options of second x-select are based on the selected value of first x-select. Eg. if I choose "Dark side" in the first x-select, items of second x-select should become "Darth Vader, Darth Sidious"; when I choose "Light side" in the first x-select, items in second x-select should become "Luke, Anakin". 

Options are filled into the second x-select correctly, but error is logged too. When I select different item in second x-select, x-select`s "value" is not changed.

**Comment by Robdel12** [comment]
Hi @horacekj! 

What version of ember are you on? I'm trying to replicate and can't seem to get the error. We also have a test [that's similar to this use case](http://thefrontside.github.io/emberx-select/#/default-value).

**Comment by Robdel12** [comment]
I'm going to close this since it's been a month now. If this is still an issue feel free to comment
